config/routes.rb
Rails.application.routes.draw do
  resources :provedors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  # Devise routes for user management
  devise_for :usuarios, skip: :registrations, :controllers => { :sessions => "usuarios/sessions" }
  devise_scope :usuario do
	resource :registration,
	only: [:new, :create, :edit, :update],
    path: 'usuarios',
    path_names: { new: 'sign_up' },
    controller: 'usuarios/registrations',
    as: :usuario_registration do
      get :cancel
    end
  end
  # Clients routes for clients management
  resources :clientes, only: [:index, :edit, :update, :create, :destroy]
  # Aseguradoras routes for aseguradoras management
  resources :aseguradoras, except: [:destroy]
  # Siniestro routes for siniestro management
  resources :siniestros, except: [:destroy]
  # Report_danos routes for report_danos management
  scope ':siniestro' do
    resources :report_danos, only: [:index, :show, :edit, :update, :create]
  end 

  resources :operarios, only: [:index]

  namespace :api, defaults: { format: "json" } do
      namespace :v1 do
        resources :fotos_autos, controller: "fotos", only: [:create]
        post '/inventarios' => 'inventarios#create', only: [:create]
        resources :extras, controller: "extras", only: [:create]
        scope ':siniestro' do
          scope ':reporte_danos' do
            resources :operaciones, controller: "operacione", only: [:create, :update, :destroy]
          end
        end
      end
  end

  # get-post-delete-put-patch '/nueva_camisa_de_rallas' => 'camisa#new', as: 'new_camisa_rallas'
end

# siniestro/:id/reporte_danos

app/models/cliente.rb
class Cliente < ApplicationRecord
	has_many :siniestro

	validates :Nombre, presence: true, length: { minimum: 7, maximum: 50}
	validates :Direccion, presence: true, length: { minimum: 5, maximum: 50}
	validates :Correo, presence: true, email: true
	validates_plausible_phone :Telefono, presence: true
	before_validation :set_phone

	private 
  def set_phone
    self.Telefono = PhonyRails.normalize_number(self.Telefono, country_code: 'MX')
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @cliente = Cliente.new
    @clientes = Cliente.all()
  end

  # GET /clientes/1/edit
  def edit
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    if @cliente.update(cliente_params)
      redirect_to clientes_path, notice: "Se ha actualizado el cliente correctamente "
      return 
    end
    render :index
  end

  def create
    @cliente = Cliente.new(cliente_params)
    if @cliente.save
          redirect_to clientes_path, notice: "Se ha registrado correctamente el cliente" 
          return
    end
    @clientes = Cliente.all()
    render :index
  end

  def destroy
    if @cliente.destroy
      redirect_to clientes_path, notice: "Se ha eliminado el cliente correctamente" 
        return
    end
     render index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:Nombre, :Direccion, :Telefono, :Correo)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for (@cliente) do |form| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col s6">
    <p>
      <%= form.label :Nombre %>
      <%= form.text_field :Nombre %>
    </p>
    <p>
      <%= form.label :Teléfono %>
      <%= form.text_field :Telefono %>
    </p>
  </div>

  <div class="col s6">
    <p>
      <%= form.label :Dirección %>
      <%= form.text_field :Direccion %>
    </p>

    <p>
      <%= form.label :Correo %>
      <%= form.text_field :Correo %>
    </p>
  </div>
</div>

<div class="col s12" align="right">
  <div class="actions">
    <%= form.submit "Registrar", class: "btn" %>
  </div>
</div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
      <div class="col s12">
            <blockquote><h3>Catálogo Clientes</h3></blockquote>
      </div>
</div>
<div class="row">
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s6"><a class="active" href="#test1">Registrar</a></li>
      <li class="tab col s6"><a href="#test2">Registrados</a></li>
    </ul>
  </div>

<div id="test1" class="col s12">
  <h5 style="background: #bbdefb;">Registrar nuevo cliente</h5>
  <%= render partial: "form"%>
</div>

<div id="test2" class="col s12">
  <h5 style="background: #bbdefb;">Listado de clientes</h5>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Dirección</th>
      <th>Teléfono</th>
      <th>Correo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.Nombre %></td>
        <td><%= cliente.Direccion %></td>
        <td><%= cliente.Telefono %></td>
        <td><%= cliente.Correo %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: 'Esta seguro que desea eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>