config/routes.rb
Rails.application.routes.draw do
  resources :provedors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  # Devise routes for user management
  devise_for :usuarios, skip: :registrations, :controllers => { :sessions => "usuarios/sessions" }
  devise_scope :usuario do
	resource :registration,
	only: [:new, :create, :edit, :update],
    path: 'usuarios',
    path_names: { new: 'sign_up' },
    controller: 'usuarios/registrations',
    as: :usuario_registration do
      get :cancel
    end
  end
  # Clients routes for clients management
  resources :clientes, only: [:index, :edit, :update, :create, :destroy]
  # Aseguradoras routes for aseguradoras management
  resources :aseguradoras, except: [:destroy]
  # Siniestro routes for siniestro management
  resources :siniestros, except: [:destroy]
  # Report_danos routes for report_danos management
  scope ':siniestro' do
    resources :report_danos, only: [:index, :show, :edit, :update, :create]
  end 

  resources :operarios, only: [:index]

  namespace :api, defaults: { format: "json" } do
      namespace :v1 do
        resources :fotos_autos, controller: "fotos", only: [:create]
        post '/inventarios' => 'inventarios#create', only: [:create]
        resources :extras, controller: "extras", only: [:create]
        scope ':siniestro' do
          scope ':reporte_danos' do
            resources :operaciones, controller: "operacione", only: [:create, :update, :destroy]
          end
        end
      end
  end

  # get-post-delete-put-patch '/nueva_camisa_de_rallas' => 'camisa#new', as: 'new_camisa_rallas'
end

# siniestro/:id/reporte_danos

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aseguradora.rb
class Aseguradora < ApplicationRecord
	has_many :siniestro

	validates :nombre, presence: true, length: { minimum: 7, maximum: 50}
end

app/models/auto.rb
class Auto < ApplicationRecord
	belongs_to :siniestro
	has_many :inventario_auto
  	has_many :inventario, through: :inventario_auto
  	has_many :fotos_auto
  	has_one :extra

  	validates :Vin, presence: true, length: { is: 17 }
  	validates :Placas, presence: true, length: { minimum: 3, maximum: 7 }
  	validates :Marca, presence: true, length: { minimum: 2, maximum: 25 }
  	validates :Modelo, presence: true, length: { minimum: 4, maximum: 25 }
  	validates :Anio, presence: true, numericality: true
  	validates :Color, presence: true, length: { minimum: 4, maximum: 10 }
end

app/models/cliente.rb
class Cliente < ApplicationRecord
	has_many :siniestro

	validates :Nombre, presence: true, length: { minimum: 7, maximum: 50}
	validates :Direccion, presence: true, length: { minimum: 5, maximum: 50}
	validates :Correo, presence: true, email: true
	validates_plausible_phone :Telefono, presence: true
	before_validation :set_phone

	private 
  def set_phone
    self.Telefono = PhonyRails.normalize_number(self.Telefono, country_code: 'MX')
  end
end

app/models/extra.rb
class Extra < ApplicationRecord
	belongs_to :auto

	validates :kilometraje, presence: true, length: { minimum: 3, maximum: 10}
  	validates :bateria, presence: true, length: { minimum: 3, maximum: 10}
  	validates :num_tapetes, presence: true, length: { is: 1 }
  	# validates :tipo_tapete, presence: true, length: { minimum: 7, maximum: 25}
  	validates :gasolina_litros, presence: true, numericality: true
  	# validates :gasolina_medida, presence: true, numericality: true
  	validates :comentarios, presence: true, length: { minimum: 5, maximum: 60}
  	validates :descr_gral, presence: true, length: { minimum: 5, maximum: 60}

  	has_one_attached :firma
  	validates :firma, presence: true, blob: { content_type: :image }
  	validates :firma, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes }

    has_one_attached :danos_preexistentes
    validates :danos_preexistentes, presence: true, blob: { content_type: :image }
    validates :danos_preexistentes, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes}

end

app/models/fotos_auto.rb
class FotosAuto < ApplicationRecord
  belongs_to :auto
  has_one_attached :foto
  validates :foto, presence: true, blob: { content_type: :image }
  validates :foto, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes }


  	def classname
		"FotosAuto"
	end
end

app/models/inventario.rb
class Inventario < ApplicationRecord

	validates :nombre, presence: true, length: { minimum: 3, maximum: 30}
	validates :activo, presence: true
	validates :categoria, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 3}

  def exterior?
  	self.categoria == 1
  end

  def interior?
  	self.categoria == 2
  end

  def mecanica?
  	self.categoria == 3
  end 
	
end

app/models/inventario_auto.rb
class InventarioAuto < ApplicationRecord
	belongs_to :inventario
	belongs_to :auto
end

app/models/operacione.rb
class Operacione < ApplicationRecord
	belongs_to :report_dano
	has_many_attached :fotos

  	scope :with_eager_loaded_fotos, -> { eager_load(fotos_attachments: :blob) }

  	scope :reparacion, -> { where(tipo: 1) }

  	scope :sustitucion, -> { where(tipo: 2) }

  	def classname
		"Reporte daños"
	end

end

app/models/provedor.rb
class Provedor < ApplicationRecord
	
end

app/models/report_dano.rb
class ReportDano < ApplicationRecord
  belongs_to :siniestro
  has_many :operacione
end

app/models/siniestro.rb
class Siniestro < ApplicationRecord
	belongs_to :aseguradora
	belongs_to :cliente
	belongs_to :usuario
	has_one :auto
	has_one :report_dano
	after_save :update_noOrden

	validates :noSiniestro, presence: true, length: { minimum: 1, maximum: 20}
	validates :tipoEntrada, presence: true, numericality: {only_integer: true, greater_than: 0, less_than_or_equal_to: 4}
	# validates :status, presence: true
	validates :fechaEntrada, presence: true
	validates :fechaSalida, presence: true

	private
	def update_noOrden
		if self.noOrden.nil? || self.noOrden.blank?
			self.update_attribute(:noOrden, 'B' + self.id.to_s)
		end
	end
end

app/models/token.rb
class Token < ApplicationRecord
	belongs_to :usuario
	before_create :generate_token

	private 
	def generate_token 
  		begin 
  			self.token = SecureRandom.hex(30)
  		end while Token.where(token: self.token).any?
	end
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :trackable

  has_many :siniestro
  has_one :token

  validates :email, email: true, uniqueness: true, length: { maximum: 50}
  validates :nombreUsuario, presence: true, uniqueness: true, length: { minimum: 3, maximum: 30} 
  validates :nombre, presence: true, length: { minimum: 3, maximum: 50}
  validates_plausible_phone :celular, presence: true
  before_validation :set_phone
  validates :tipo, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 4}

  def admin?
  	self.tipo == 1
  end

  def secretary?
  	self.tipo == 2
  end

  def asesor?
  	self.tipo == 3
  end 

   def otros?
    self.tipo == 4
  end 

  def email=(address)
    if new_record?
      write_attribute(:email, address)
    end
  end

  def nombreUsuario=(name)
    if new_record?
      write_attribute(:nombreUsuario, name)
    end
  end

  private 
  def set_phone
    self.celular = PhonyRails.normalize_number(self.celular, country_code: 'MX')
  end
  
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/operarios_helper.rb
module OperariosHelper
end

app/helpers/provedors_helper.rb
module ProvedorsHelper
end

app/helpers/siniestro_helper.rb
module SiniestroHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pits</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/signature_pad/1.5.3/signature_pad.min.js"></script>
    <%= javascript_include_tag 'application' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/roundSlider/1.3.2/roundslider.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/roundSlider/1.3.2/roundslider.min.css" rel="stylesheet"/>
    
  </head>

  <body>
    <div class="container">
      <div class="header">
        <%= render "/partials/navigation" %>
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
      </div>
      <div class="body">
        <%= yield %>
      </div>
      <div class="footer top-space">
        <div class="footer-container">
          <p class="text-muted">Desarrollado por Melisa</p>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
  <meta charset="utf-8">
</head>
<body>
	<div class="header">
		<H6>
			<span class="big">PITS AUTOMOTRIZ</span><br />
			La Ronda 16, Acapantzingo c.p. 62440 Cuernavaca, Morelos<br />
			Tel&eacute;fono: (777) 2280570 al 73
		</H6>
    </div>
    <div class='container'>
    	<%= yield %>
  	</div>
</body>
</html>

app/views/partials/_navigation.html.erb
<% if usuario_signed_in? %>
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to "Editar cuenta", edit_usuario_registration_path %></li>
  <li><%= link_to "Cerrar Sesión", destroy_usuario_session_path, method: :delete %></li>
</ul>
<% if @c_user.asesor? %>
<ul id="dropdown2" class="dropdown-content">
  <li><%= link_to "Registrar siniestro", new_siniestro_path %></li>
  <li><%= link_to "Lista siniestro", siniestros_path%></li>
</ul>
<% end %>
<ul id="dropdown3" class="dropdown-content">
  <li><%= link_to "Usuarios", operarios_path%></li>
  <li><%= link_to "Clientes", clientes_path%></li>
  <li><%= link_to "Proveedores", provedors_path%></li>
</ul>
<% end %>

<nav>
  <div class="nav-wrapper">
    <%= link_to "Pits Automotriz", root_path, class: "brand-logo" %>
    <a data-target="side-nav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <!-- Navbar oculto -->
    <ul id="side-nav" class="sidenav">
      <% if usuario_signed_in? %>
        <% if @c_user.asesor? %>
          <ul class="collapsible collapsible-accordion">
            <li>
              <a class="collapsible-header">Siniestros<i class="material-icons">arrow_drop_down</i></a>
              <div class="collapsible-body">
                <ul>
                  <li><%= link_to "Registrar siniestro", new_siniestro_path %></li>
                  <li><%= link_to "Lista siniestro", siniestros_path%></li>
                </ul>
              </div>
            </li>
          </ul>
        <% else %>
          <li><%= link_to "Registrar nuevo usuario", new_usuario_registration_path %></li>
        <% end %>
        <ul class="collapsible collapsible-accordion">
          <li>
            <a class="collapsible-header">Cuenta<i class="material-icons">arrow_drop_down</i></a>
            <div class="collapsible-body">
              <ul>
                <li><%= link_to "Editar cuenta", edit_usuario_registration_path %></li>
                <li><%= link_to "Cerrar Sesión", destroy_usuario_session_path, method: :delete %></li>
              </ul>
            </div>
          </li>
        </ul>
      <% else %>
        <li><%= link_to "Iniciar sesión", new_usuario_session_path %></li>
      <% end %>
      <ul class="collapsible collapsible-accordion">
        <li>
          <a class="collapsible-header">Catálogo<i class="material-icons">arrow_drop_down</i></a>
          <div class="collapsible-body">
            <ul>
              <li><%= link_to "Usuarios", operarios_path %></li>
              <li><%= link_to "Clientes", clientes_path %></li>
              <li><%= link_to "Proveedores", provedors_path%></li>
            </ul>
          </div>
        </li>
      </ul>
    </ul>

    <!-- Navbar-->
    <ul class="right hide-on-med-and-down">
      <% if usuario_signed_in? %>
        <% if @c_user.asesor? %>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Sinestros<i class="material-icons right">arrow_drop_down</i></a></li>
        <% else %>
          <li><%= link_to "Registrar nuevo usuario", new_usuario_registration_path %></li>
        <% end %>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown3">Catálogos<i class="material-icons right">arrow_drop_down</i></a></li>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Cuenta<i class="material-icons right">arrow_drop_down</i></a></li>
      <% else %>
        <li><%= link_to "Iniciar sesión", new_usuario_session_path %></li>
      <% end %>
      
    </ul>
  </div>
</nav>