config/routes.rb
Rails.application.routes.draw do
  resources :provedors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  # Devise routes for user management
  devise_for :usuarios, skip: :registrations, :controllers => { :sessions => "usuarios/sessions" }
  devise_scope :usuario do
	resource :registration,
	only: [:new, :create, :edit, :update],
    path: 'usuarios',
    path_names: { new: 'sign_up' },
    controller: 'usuarios/registrations',
    as: :usuario_registration do
      get :cancel
    end
  end
  # Clients routes for clients management
  resources :clientes, only: [:index, :edit, :update, :create, :destroy]
  # Aseguradoras routes for aseguradoras management
  resources :aseguradoras, except: [:destroy]
  # Siniestro routes for siniestro management
  resources :siniestros, except: [:destroy]
  # Report_danos routes for report_danos management
  scope ':siniestro' do
    resources :report_danos, only: [:index, :show, :edit, :update, :create]
  end 

  resources :operarios, only: [:index]

  namespace :api, defaults: { format: "json" } do
      namespace :v1 do
        resources :fotos_autos, controller: "fotos", only: [:create]
        post '/inventarios' => 'inventarios#create', only: [:create]
        resources :extras, controller: "extras", only: [:create]
        scope ':siniestro' do
          scope ':reporte_danos' do
            resources :operaciones, controller: "operacione", only: [:create, :update, :destroy]
          end
        end
      end
  end

  # get-post-delete-put-patch '/nueva_camisa_de_rallas' => 'camisa#new', as: 'new_camisa_rallas'
end

# siniestro/:id/reporte_danos

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aseguradora.rb
class Aseguradora < ApplicationRecord
	has_many :siniestro

	validates :nombre, presence: true, length: { minimum: 7, maximum: 50}
end

app/models/auto.rb
class Auto < ApplicationRecord
	belongs_to :siniestro
	has_many :inventario_auto
  	has_many :inventario, through: :inventario_auto
  	has_many :fotos_auto
  	has_one :extra

  	validates :Vin, presence: true, length: { is: 17 }
  	validates :Placas, presence: true, length: { minimum: 3, maximum: 7 }
  	validates :Marca, presence: true, length: { minimum: 2, maximum: 25 }
  	validates :Modelo, presence: true, length: { minimum: 4, maximum: 25 }
  	validates :Anio, presence: true, numericality: true
  	validates :Color, presence: true, length: { minimum: 4, maximum: 10 }
end

app/models/cliente.rb
class Cliente < ApplicationRecord
	has_many :siniestro

	validates :Nombre, presence: true, length: { minimum: 7, maximum: 50}
	validates :Direccion, presence: true, length: { minimum: 5, maximum: 50}
	validates :Correo, presence: true, email: true
	validates_plausible_phone :Telefono, presence: true
	before_validation :set_phone

	private 
  def set_phone
    self.Telefono = PhonyRails.normalize_number(self.Telefono, country_code: 'MX')
  end
end

app/models/extra.rb
class Extra < ApplicationRecord
	belongs_to :auto

	validates :kilometraje, presence: true, length: { minimum: 3, maximum: 10}
  	validates :bateria, presence: true, length: { minimum: 3, maximum: 10}
  	validates :num_tapetes, presence: true, length: { is: 1 }
  	# validates :tipo_tapete, presence: true, length: { minimum: 7, maximum: 25}
  	validates :gasolina_litros, presence: true, numericality: true
  	# validates :gasolina_medida, presence: true, numericality: true
  	validates :comentarios, presence: true, length: { minimum: 5, maximum: 60}
  	validates :descr_gral, presence: true, length: { minimum: 5, maximum: 60}

  	has_one_attached :firma
  	validates :firma, presence: true, blob: { content_type: :image }
  	validates :firma, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes }

    has_one_attached :danos_preexistentes
    validates :danos_preexistentes, presence: true, blob: { content_type: :image }
    validates :danos_preexistentes, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes}

end

app/models/fotos_auto.rb
class FotosAuto < ApplicationRecord
  belongs_to :auto
  has_one_attached :foto
  validates :foto, presence: true, blob: { content_type: :image }
  validates :foto, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes }


  	def classname
		"FotosAuto"
	end
end

app/models/inventario.rb
class Inventario < ApplicationRecord

	validates :nombre, presence: true, length: { minimum: 3, maximum: 30}
	validates :activo, presence: true
	validates :categoria, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 3}

  def exterior?
  	self.categoria == 1
  end

  def interior?
  	self.categoria == 2
  end

  def mecanica?
  	self.categoria == 3
  end 
	
end

app/models/inventario_auto.rb
class InventarioAuto < ApplicationRecord
	belongs_to :inventario
	belongs_to :auto
end

app/models/operacione.rb
class Operacione < ApplicationRecord
	belongs_to :report_dano
	has_many_attached :fotos

  	scope :with_eager_loaded_fotos, -> { eager_load(fotos_attachments: :blob) }

  	scope :reparacion, -> { where(tipo: 1) }

  	scope :sustitucion, -> { where(tipo: 2) }

  	def classname
		"Reporte daños"
	end

end

app/models/provedor.rb
class Provedor < ApplicationRecord
	
end

app/models/report_dano.rb
class ReportDano < ApplicationRecord
  belongs_to :siniestro
  has_many :operacione
end

app/models/siniestro.rb
class Siniestro < ApplicationRecord
	belongs_to :aseguradora
	belongs_to :cliente
	belongs_to :usuario
	has_one :auto
	has_one :report_dano
	after_save :update_noOrden

	validates :noSiniestro, presence: true, length: { minimum: 1, maximum: 20}
	validates :tipoEntrada, presence: true, numericality: {only_integer: true, greater_than: 0, less_than_or_equal_to: 4}
	# validates :status, presence: true
	validates :fechaEntrada, presence: true
	validates :fechaSalida, presence: true

	private
	def update_noOrden
		if self.noOrden.nil? || self.noOrden.blank?
			self.update_attribute(:noOrden, 'B' + self.id.to_s)
		end
	end
end

app/models/token.rb
class Token < ApplicationRecord
	belongs_to :usuario
	before_create :generate_token

	private 
	def generate_token 
  		begin 
  			self.token = SecureRandom.hex(30)
  		end while Token.where(token: self.token).any?
	end
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :trackable

  has_many :siniestro
  has_one :token

  validates :email, email: true, uniqueness: true, length: { maximum: 50}
  validates :nombreUsuario, presence: true, uniqueness: true, length: { minimum: 3, maximum: 30} 
  validates :nombre, presence: true, length: { minimum: 3, maximum: 50}
  validates_plausible_phone :celular, presence: true
  before_validation :set_phone
  validates :tipo, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 4}

  def admin?
  	self.tipo == 1
  end

  def secretary?
  	self.tipo == 2
  end

  def asesor?
  	self.tipo == 3
  end 

   def otros?
    self.tipo == 4
  end 

  def email=(address)
    if new_record?
      write_attribute(:email, address)
    end
  end

  def nombreUsuario=(name)
    if new_record?
      write_attribute(:nombreUsuario, name)
    end
  end

  private 
  def set_phone
    self.celular = PhonyRails.normalize_number(self.celular, country_code: 'MX')
  end
  
end

app/controllers/operarios_controller.rb
class OperariosController < ApplicationController
	before_action :set_new_user

	def set_new_user
		@usuario = Usuario.new
	end

	def index
		@usuarios = Usuario.all()

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/operarios_helper.rb
module OperariosHelper
end

app/helpers/provedors_helper.rb
module ProvedorsHelper
end

app/helpers/siniestro_helper.rb
module SiniestroHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/operarios/_new.html.erb
  <h5 style="background: #bbdefb;">Registrar nuevo usuario</h5>

  <%= form_for(@usuario, url:  usuario_registration_path) do |f| %>
    
<div class="row">
  <div class="col s4">
      <p>
        <%= f.label :tipo, "Tipo de usuario" %>
        <%= f.select(:tipo, options_for_select([['Administrador', 1], ['Secretaria(o)', 2], ['Asesor', 3], ['Otros',4]])) %>
      </p>
      <p>
        <%= f.label :password, "Contraseña"%>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> caracteres mínimos)</em>
        <% end %>
        <%= f.password_field :password, autocomplete: "new-password" %>
      </p>
      <p>
        <%= f.label :celular, "Celular" %>
        <%= f.text_field :celular%>
      </p>
  </div>

  <div class="col s4">
    <p>
      <%= f.label :nombreUsuario, "Nombre de usuario" %>
      <%= f.text_field :nombreUsuario %>
    </p>
    <p>
      <%= f.label :password_confirmation, "Confirma tu contraseña" %>
      <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </p>
  </div>

  <div class="col s4">
    <p>
      <%= f.label :nombre, "Nombre completo" %>
      <%= f.text_field :nombre %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </p>
  </div>
    
</div>
 
 <div class="col s12" align="right">
  <div class="actions">
    <%= f.submit "Registrar", class: "btn" %>
  </div>
</div>
  <% end %>

app/views/operarios/index.html.erb
<div class="row">
      <div class="col s12">
            <blockquote><h3>Catálogo Usuarios</h3></blockquote>
      </div>
</div>
<div class="row">
	<div class="col s12">
		<ul class="tabs">
			<li class="tab col s6"><a class="active" href="#test1">Registrar</a></li>
			<li class="tab col s6"><a href="#test2">Registrados</a></li>
		</ul>
	</div>

	<div id="test1" class="col s12">
        	<%= render :partial => "new"%>
	</div>

	<div id="test2" class="col s12">
			<h5 style="background: #bbdefb;">Listado de usuarios</h5>
			<table id="tablausuarios">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Puesto</th>
						<th>Teléfono</th>
						<th>Correo</th>
					</tr>
				</thead>
				<tbody>
					<%@usuarios.each do |s| %>
					<tr>
						<td><%= s.nombre %></td>
						<td><%= s.tipo %></td>
						<td><%= s.celular %></td>
						<td><%= s.email %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
	</div>
</div>