config/routes.rb
Rails.application.routes.draw do
  resources :provedors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  # Devise routes for user management
  devise_for :usuarios, skip: :registrations, :controllers => { :sessions => "usuarios/sessions" }
  devise_scope :usuario do
	resource :registration,
	only: [:new, :create, :edit, :update],
    path: 'usuarios',
    path_names: { new: 'sign_up' },
    controller: 'usuarios/registrations',
    as: :usuario_registration do
      get :cancel
    end
  end
  # Clients routes for clients management
  resources :clientes, only: [:index, :edit, :update, :create, :destroy]
  # Aseguradoras routes for aseguradoras management
  resources :aseguradoras, except: [:destroy]
  # Siniestro routes for siniestro management
  resources :siniestros, except: [:destroy]
  # Report_danos routes for report_danos management
  scope ':siniestro' do
    resources :report_danos, only: [:index, :show, :edit, :update, :create]
  end 

  resources :operarios, only: [:index]

  namespace :api, defaults: { format: "json" } do
      namespace :v1 do
        resources :fotos_autos, controller: "fotos", only: [:create]
        post '/inventarios' => 'inventarios#create', only: [:create]
        resources :extras, controller: "extras", only: [:create]
        scope ':siniestro' do
          scope ':reporte_danos' do
            resources :operaciones, controller: "operacione", only: [:create, :update, :destroy]
          end
        end
      end
  end

  # get-post-delete-put-patch '/nueva_camisa_de_rallas' => 'camisa#new', as: 'new_camisa_rallas'
end

# siniestro/:id/reporte_danos

app/models/siniestro.rb
class Siniestro < ApplicationRecord
	belongs_to :aseguradora
	belongs_to :cliente
	belongs_to :usuario
	has_one :auto
	has_one :report_dano
	after_save :update_noOrden

	validates :noSiniestro, presence: true, length: { minimum: 1, maximum: 20}
	validates :tipoEntrada, presence: true, numericality: {only_integer: true, greater_than: 0, less_than_or_equal_to: 4}
	# validates :status, presence: true
	validates :fechaEntrada, presence: true
	validates :fechaSalida, presence: true

	private
	def update_noOrden
		if self.noOrden.nil? || self.noOrden.blank?
			self.update_attribute(:noOrden, 'B' + self.id.to_s)
		end
	end
end

app/controllers/siniestros_controller.rb
class SiniestrosController < ApplicationController
	before_action :authenticate_user
	before_action :authenticate_asesor!
	before_action :set_siniestro, only: [:show, :edit, :update]
	before_action :set_cliente, only: [:create]
	before_action :set_siniestro_auto, only: [:new]
	before_action :set_aseguradoras, only: [:new, :edit]
	before_action :set_asesores, only: [:new, :edit]
	before_action :set_aseguradora, only: [:create, :update]
	before_action :set_asesor, only: [:create, :update]
	before_action :set_inventario, only: [:show]
	before_action :set_imagenes, only: [:show]

	def index
		@siniestros = Siniestro.all()

	end

	def show
		respond_to do |format|
			format.html
			format.pdf {
				render pdf: 'reporteSiniestro', 
				type: 'application/pdf',
				template: 'siniestros/reporteSiniestro',
				layout: 'pdf.html',
				disposition: 'attachment'
			}
		end
	end

	def new

	end

	def create
		# raise params.to_yaml
		@siniestro = Siniestro.new(siniestro_params)
		@siniestro.aseguradora = @aseguradora
		@siniestro.usuario = @asesor
		@siniestro.build_auto(auto_params)
		@siniestro.cliente = @cliente
		if @siniestro.auto.valid?
			if @cliente.valid?
				if @siniestro.save
					redirect_to @siniestro, notice: "Se ha registrado correctamente el siniestro" 
					return
				end
			end
		end
		set_aseguradoras
		set_asesores
		render :new
	end

	def edit
	end

	def update
	end

	private 
	def cliente_params
		params.permit(:Nombre, :Direccion, :Telefono, :Correo)
	end

	def siniestro_params
		params.require(:siniestro).permit(:noSiniestro, :poliza, :tipoEntrada, :fechaEntrada, :fechaSalida)
	end

	def set_aseguradora
		@aseguradora = Aseguradora.find(params[:siniestro][:aseguradora_id])
	end

	def set_asesor
		@asesor = Usuario.find(params[:siniestro][:usuario_id])
	end

	def auto_params
		params[:siniestro].require(:auto).permit(:Vin, :Placas, :Marca, :Modelo, :Anio, :Color)
	end

	def set_siniestro
		@siniestro = Siniestro.find(params[:id])
		if @siniestro.nil?
			redirect_to :index, alert: "No existe el siniestro"
		end
	end

	def set_cliente
		if Cliente.exists?(params[:cliente_id])
			@cliente = Cliente.find(params[:cliente_id])
			@cliente.update(cliente_params)
		else
			@cliente = Cliente.new(cliente_params)
		end
	end

	def set_siniestro_auto
		@siniestro = Siniestro.new()
		@siniestro.build_auto
	end

	def set_aseguradoras
		@aseguradoras = Aseguradora.all()
	end

	def set_asesores
		@asesores = Usuario.all.where("tipo = 3")
	end

	def set_inventario
		@inventarioExteriores = Inventario.where(activo: true, categoria: 1).order(:id)
		@inventarioInteriores = Inventario.where(activo: true, categoria: 2).order(:id)
		@inventarioMecanica = Inventario.where(activo: true, categoria: 3).order(:id)
		@inventarios = @siniestro.auto.inventario_auto
		@extra = @siniestro.auto.extra
	end

	def set_imagenes
		unless @siniestro.nil?
			auto = @siniestro.auto
			unless auto.nil?
				@fotos = auto.fotos_auto
			end
		end
	end

end

app/helpers/siniestro_helper.rb
module SiniestroHelper
end

app/views/siniestros/_form.html.erb
<%= form_for([@siniestro]) do |f| %>
	<% if @siniestro.errors.any? %>
		<div class="alert">
			<ul type = "circle">
				<li><i class="material-icons small">report_problem</i>
				<strong>Error al realizar la operación:</strong></li>
				<% @siniestro.errors.full_messages.each do |message| %>
				<li><i class="material-icons tiny">error</i><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<% if @siniestro.auto.errors.any? %>
		<div class="alert">
			<ul type = "circle">
				<li><i class="material-icons small">report_problem</i>
				<strong>Error al realizar la operación:</strong></li>
				<% @siniestro.auto.errors.full_messages.each do |message| %>
				<li><i class="material-icons tiny">error</i><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<% if !@siniestro.cliente.nil? && @siniestro.cliente.errors.any? %>
		<div class="alert">
			<ul type = "circle">
				<li><i class="material-icons small">report_problem</i>
				<strong>Error al realizar la operación:</strong></li>
				<% @siniestro.cliente.errors.full_messages.each do |message| %>
				<li><i class="material-icons tiny">error</i><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<h5>Siniestro</h5>
	<div class="row">
		<div class="col s4">
			<div class="field">
				<p>
					<%= f.label :noSiniestro, "Número de siniestro" %>
			    	<%= f.text_field :noSiniestro %>
			    </p>
		    </div>
		</div>
		<div class="col s4">
			<div class="field">
				<p>
					<%= f.label :usuario_id, "Asesor" %>
		      		<%= f.select(:usuario_id, options_from_collection_for_select(@asesores, :id, :nombre)) %>
			    </p>
		    </div>
		</div>
		<div class="col s4">
			<div class="field">
				<p>
					<%= f.label :aseguradora_id, "Aseguradora" %>
		      		<%= f.select(:aseguradora_id, options_from_collection_for_select(@aseguradoras, :id, :nombre)) %>
			    </p>
		    </div>
		</div>
	</div>

	<div class="row">
		<div class="col s3">
			<div class="field">
			    <p>
			    	<%= f.label :poliza, "Poliza" %>
		      		<%= f.text_field :poliza %>
		      	</p>
		    </div>
		</div>
		<div class="col s3">
			<div class="field">
				<p>
					<%= f.label :tipoEntrada, "Tipo entrada" %>
      				<%= f.select(:tipoEntrada, options_for_select([['Rodando', 1], ['En grua', 2], ['Transito', 3], ['Pago daños', 4] ])) %>
			    </p>
		    </div>
		</div>
		<div class="col s3">
			<div class="field">
		      	<p>
		      		<%= f.label :fechaEntrada, "Fecha de entrada" %>
     				<%= f.text_field :fechaEntrada, class:"datepicker" %>
		      	</p>
		    </div>
		</div>
		<div class="col s3">
			<div class="field">
		      	<p>
		      		<%= f.label :fechaSalida, "Fecha de salida" %>
      				<%= f.text_field :fechaSalida, class:"datepicker" %>
		      	</p>
		    </div>
		</div>
	</div>

	<h5>Cliente</h5>
	<input type="hidden" id="id_cliente", name="cliente_id">
	<div class="field">
    	<label for="Nombre"> Nombre</label>
        <input type="text" id="Nombre" name="Nombre" value=""/>
  	</div>

  	<div class="field">
    	<label for="Direccion"> Dirección</label>
        <input type="text" id="Direccion" name="Direccion" value=""/>
  	</div>

  	<div class="field">
    	<label for="Telefono"> Teléfono</label>
        <input type="text" id="Telefono" name="Telefono" value=""/>
  	</div>

  	<div class="field">
    	<label for="Correo"> Correo</label>
        <input type="email" id="Correo" name="Correo" value=""/>
  	</div>

	<div class="row">
			<%= f.fields_for @siniestro.auto do |auto_form|%>
				<h5>Auto</h5>
				<div class="col s6">
					<div class="field">
						<p>
							<%= auto_form.label :Vin, "Numero de serie"%>
				    		<%= auto_form.text_field :Vin %>
					    </p>
					     <p>
					    	<%= auto_form.label :Marca, "Marca"%>
			    			<%= auto_form.text_field :Marca %>
					    </p>
					    <p>
							<%= auto_form.label :Color, "Color"%>
			    			<%= auto_form.text_field :Color %>
					    </p>
					</div>
				</div>
				<div class="col s6">
					<div class="field">
					    <p>
					    	<%= auto_form.label :Placas, "Placas"%>
			    			<%= auto_form.text_field :Placas %>
					    </p>
					   	<p>
							<%= auto_form.label :Modelo, "Modelo"%>
			    			<%= auto_form.text_field :Modelo %>
					    </p>
					    <p>
							<%= auto_form.label :Anio, "Año"%>
			    			<%= auto_form.text_field :Anio %>
					    </p>
					</div>
				</div>			
			<% end %>
		</div>
	

	<div class="actions">
      <%= f.submit "Registrar", class: "btn" %>
    </div>
<% end %>

app/views/siniestros/index.html.erb
<table id="tablaSiniestros">
	<thead>
		<tr>
			<th>No Siniestro</th>
			<th>Cliente</th>
			<th>Automovil</th>
			<th>Aseguradora</th>
			<th>Ingreso</th>
			<th>Salida</th>
			<th>Acciones</th>
		</tr>
	</thead>
	<tbody>
		<%@siniestros.each do |s| %>
		<tr>
			<td><%= s.noOrden %></td>
			<td><%= s.cliente.Nombre %></td>
			<td><%= s.auto.Marca + ' ' + s.auto.Modelo + ' ' + s.auto.Anio %></td>
			<td><%= s.aseguradora.nombre %></td>
			<td><%= s.fechaEntrada %></td>
			<td><%= s.fechaSalida %></td>
			<td>
				<%= link_to siniestro_path(s) do %>
                	<i class="material-icons">drive_eta</i>
                <% end %>
                <% if s.report_dano.nil? %>
	                <%= link_to report_danos_path(s) do %>
	                	<i class="material-icons">assignment</i>
	                <% end %>
	            <%  else %>
	             	<%= link_to edit_report_dano_path(s, s.report_dano) do %>
	                	<i class="material-icons">assignment</i>
	                <% end %>
	            <% end %>
            </td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/siniestros/new.html.erb
<h4>Registrar siniestro</h4>

<%= render 'form', siniestro: @siniestro %>

app/views/siniestros/reporteSiniestro.pdf.erb
<H4 style="color: #1a237e">ORDEN DE INGRESO</H4>
<hr>
<div class="row">
	<div class="colS3">
		<p>
			<strong>No. de orden: <%= @siniestro.noOrden %></strong><br /><br />
			<strong>Entrada:</strong> <%= @siniestro.fechaEntrada %><br />
			<strong>Salida tentativa:</strong> <%= @siniestro.fechaSalida %><br />
			<strong>Placas:</strong> <%= @siniestro.auto.Placas %><br />
			<strong>Serie:</strong> <%= @siniestro.auto.Vin %><br />
			<strong>Vehiculo:</strong> <%= @siniestro.auto.Marca + ' ' + @siniestro.auto.Modelo + ' ' + @siniestro.auto.Anio %><br />
		</p>
	</div>
	<div class="colS3">
		<p>
			<%= wicked_pdf_image_tag "logoPits.jpg"%>
		</p>
	</div>
	<div class="colS3">
		<p>
			<strong>Asesor: <%= @siniestro.usuario.nombre %></strong><br /><br />
			<strong>Cliente:</strong> <%= @siniestro.cliente.Nombre %><br />
			<strong>Dirección:</strong> <%= @siniestro.cliente.Direccion %><br />
			<strong>Aseguradora:</strong> <%= @siniestro.aseguradora.nombre %><br />
			<strong>E-mail:</strong> <%= @siniestro.cliente.Correo %><br />
			<strong>Telefono:</strong> <%=@siniestro.cliente.Telefono %><br />
		</p>
	</div>
</div>
<div class="row">
	<div class="colS1">
		<H4 style="color: #1a237e">INVENTARIO</H4>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col s4">
	<div class="colS5">
		<H5 style="color: #1a237e">EXTERIORES</H5>
		<%@inventarioExteriores.each do |i| %>
            <p>
                  <label>
                        <% if @inventarios.find_by(inventario_id: i.id).nil? %>
                              <input  type="checkbox" name="inventarios[]">
                        <% else %>
                              <input  type="checkbox" checked="checked" name="inventarios[]">
                        <% end %>
                        <span><%= i.nombre %></span>
                  </label>
            </p>
      <% end %>
	      <p>
	      	<strong>Kilometraje:  </strong><%= @extra.kilometraje %><br/><br/>
			<strong>Bateria:  </strong><%= @extra.bateria %><br/><br/>
			<strong>No. de tapetes:  </strong><%= @extra.num_tapetes %><br/><br/>
			<strong>Gasolina:  </strong><%= @extra.gasolina_litros %><br/><br/>
	      </p>
	</div>
	<div class="colS3">
		<H5 style="color: #1a237e">INTERIORES</H5>
		<%@inventarioInteriores.each do |i| %>
            <p>
                  <label>
                        <% if @inventarios.find_by(inventario_id: i.id).nil? %>
                        <input  type="checkbox" name="inventarios[]" class="filled-in" value="<%= i.id %>">
                        <% else %>
                              <input  type="checkbox" checked="checked" name="inventarios[]" class="filled-in" value="<%= i.id %>" >
                        <% end %>
                        <span><%= i.nombre %></span>
                  </label>
            </p>
      	<% end %>
		<H5 style="color: #1a237e">MECANICA</H5>
        <%@inventarioMecanica.each do |i| %>
              <p>
                    <label>
                          <% if @inventarios.find_by(inventario_id: i.id).nil? %>
                          <input  type="checkbox" name="inventarios[]" class="filled-in" value="<%= i.id %>">
                          <% else %>
                                <input  type="checkbox" checked="checked" name="inventarios[]" class="filled-in" value="<%= i.id %>" >
                          <% end %>
                          <span><%= i.nombre %></span>
                    </label>
              </p>
        <% end %>
	</div>
	<div class="col S2" style="display:table-cell; vertical-align:middle; text-align:center">
		<p>
			<H5 style="color: #1a237e">DAÑOS PREEXISTENTES</H5>
			<%= image_tag @extra.danos_preexistentes, class:'imageDanos' %><br />
			<%= image_tag @extra.firma, class: 'imagFirma' %>
			<hr class="linea">
			<H4 style= "margin-bottom: 0;">FIRMA DE CONFORMIDAD</H4>
			<H7>Autorizo la revisión de los puntos de seguridad</H7>
		</p>
	</div>
</div>
</div>

<div class="row">
	<div class="colS1">
		<p>
			<strong>Comentarios: </strong><%= @extra.comentarios %><br/><br/>
			<strong>Descripción general del golpe: </strong><%= @extra.descr_gral %><br />
		</p>
	</div>
</div>